FROM wordpress:php7.4-fpm-alpine

RUN apk --no-cache --virtual .build-deps add \
        autoconf gcc make g++ zlib-dev && \
    pecl install redis && \
    docker-php-ext-enable redis && \
    apk del .build-deps
